exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: CC-BY-4.0
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/etiennecollin/gamma-distribution"

title: The Gamma Distribution
description: This is a paper outlining the various properties and applications of the gamma distribution.